backend:
  name: github
  repo: NielsSarys/nielssarys.github.io
  branch: master

publish_mode: editorial_workflow

media_folder: "src"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
- {label: "Texte", name: "body", widget: "markdown"}